wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1662662722
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 16
      4: 3.8.8
      5: 0.12.14
      8:
      - 5
batch_size:
  desc: null
  value: 8
epochs:
  desc: null
  value: 1
img_size:
  desc: null
  value: (512,512)
lamda:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0003
lr_decay:
  desc: null
  value: 0.1
optimizer:
  desc: null
  value: adam
save_path:
  desc: null
  value: ./weights/model_vit_hd1_1.pth
with_augmentation:
  desc: null
  value: true
