maintainer: Mohamed Amine Dhiab

device: cuda:0 #device on which you want to train the data, use cpu if no nvidia cuda driver is available.

run_name: test_kaggle

job_type: kaggle_job

img_dir: ../data/ignore/image # directory to image data

mask_dir: ./data/ignore/image_mask # directory to image masks

label_dir: ./data/ignore/WSI_metada # directory to image labels

pipeline:
    - name: process # process pipe used to prepare the data
      train_fraction: 0.75 # proportion of the data to be used for training
      validation_fraction: 0.15 # proportion of the data to be used for validation
      is_augment: false # augmentation will be executed if this is true
    - name: train # train pipe used to training the model
      train_cfg:
          with_augmentation: false # if set to true, data in the '.../augmented' folder will be used for training
          img_size: (384,384)
          epochs: 5
          batch_size: 8
          learning_rate: 0.0003
          lr_decay: 0.1
          lamda: 1
          optimizer: adam
          save_path: ./weights/model_kaggle_test.pth
    - name: test # test pipe used to run inference
      test_data: ./data/ignore/test.tsv
      test_cfg:
          img_size: (384,384)
          batch_size: 8
          weights: ./weights/model_kaggle_test.pth

with_wandb: false

multi_gpus: false # not supported yet

model_cfg: densenet.yml

random_seed: 2022
