wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: huggingface
    huggingface_version: 3.0.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1652379639
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 53
      - 55
      3:
      - 1
      - 2
      - 13
      - 16
      4: 3.8.8
      5: 0.12.14
      6: 3.0.0
      8:
      - 1
      - 5
architecture:
  desc: null
  value: DensenetGuSA
batch_size:
  desc: null
  value: 5
classes:
  desc: null
  value: 4
dataset:
  desc: null
  value: GRAZ
epochs:
  desc: null
  value: 50
lamda:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0005
