wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: huggingface
    huggingface_version: 3.0.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1656507791
    t:
      1:
      - 1
      - 3
      - 5
      - 11
      - 41
      - 53
      - 55
      2:
      - 1
      - 3
      - 5
      - 11
      - 41
      - 53
      - 55
      3:
      - 2
      - 13
      4: 3.8.8
      5: 0.12.14
      6: 3.0.0
      8:
      - 5
