wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: huggingface
    huggingface_version: 4.21.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1662195412
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 13
      - 16
      4: 3.8.8
      5: 0.12.14
      6: 4.21.1
      8:
      - 5
attention_threshold:
  desc: null
  value: 0.5
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 1
img_size:
  desc: null
  value: None
lamda:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0003
lr_decay:
  desc: null
  value: 0.1
optimizer:
  desc: null
  value: adam
save_path:
  desc: null
  value: ./weights/model_vit_dino_dev.pth
with_augmentation:
  desc: null
  value: false
