wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: huggingface
    huggingface_version: 4.21.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1660442520
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 1
      - 2
      - 3
      - 13
      4: 3.8.8
      5: 0.12.14
      6: 4.21.1
      8:
      - 5
